server:
  port: 8006
spring:
  application:
    name: consul-provider-8006
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xieyc@mysql
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:    # \u6307\u5B9A\u6CE8\u518C\u5BF9\u5916\u66B4\u9732\u7684\u670D\u52A1\u540D\u79F0
        service-name: ${spring.application.name}
