server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此配置绑定的消息中间件信息
        defaultRabbit:
          type: rabbit
          environment:  # 消息中间件环境配置
            spring:
              rabbitmq:
                host: 192.168.0.50
                port: 5672
                username: guest
                password: guest
      bindings:  # 服务整合处理
        output:   # 表示生产者
          destination: ycExchange  # 指定交换机
          content-type: application/json  # 消息编码格式
          bindner: defaultRabbit
