server:
  port: 8001

spring:
  application:
    name: cloud-eureka-hystrix-provider-pay-service   # 服务提供者集群中,相同服务的节点要写的一样，这是这个集群的关键

eureka:
  client:
    # 注册进eureka服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      #  设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: pay8001  # 修改 在Eureka 注册中心显示的 主机名
    prefer-ip-address: true   # 访问路径可以显示IP地址
