server:
  port: 8802
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此配置绑定的消息中间件信息
        defaultRabbit:
          type: rabbit
          environment:  # 消息中间件环境配置
            spring:
              rabbitmq:
                host: 192.168.0.50
                port: 5672
                username: guest
                password: guest
      bindings:
        input:   # 表示消费者
          destination: ycExchange  # 指定交换机
          content-type: application/json  # 消息文本格式
          bindner: defaultRabbit
          group: yc
